version: '3.8'

volumes:
  jellyfin_data: {}
  radarr_data: {}
  sonarr_data: {}
  bazarr_data: {}
  prowlarr_data: {}
  deluge_data: {}

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/root/server.crt
      - ./server.key:/root/server.key
    ports:
      - 80:80
      - 443:443
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - jellyfin_data:/config
      - ${MOVIES_DIR}:/data/movies
      - ${TVSHOWS_DIR}:/data/tvshows
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - radarr_data:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR}:/downloads
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - sonarr_data:/config
      - ${TVSHOWS_DIR}:/tv
      - ${DOWNLOADS_DIR}:/downloads
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - bazarr_data:/config
      - ${MOVIES_DIR}:/movies
      - ${TVSHOWS_DIR}:/tv
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - prowlarr_data:/config
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - deluge_data:/config
      - ${DOWNLOADS_DIR}:/downloads
